name: "SEO Broken Link Checker"
author: "Sebastián Iturralde"
description: "Checks your website sitemap for broken links and generates a report."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "link-2"
  color: "red"
inputs:
  email:
    description: The commiter's email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The committer's name
    required: true
    default: ${{ github.actor }}